return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "astro-language-server",
      -- "biome",
      -- "emmet-language-server",
      -- "eslint_d",
      -- "eslint-lsp",
      "hclfmt",
      -- "ltex-ls",
      "markdownlint-cli2",
      "markdown-toc",
      -- "marksman",
      "markdown-oxide",
      -- "mdslw",
      "nil",
      "oxfmt",
      "oxlint",
      "stylua",
      "tinymist",
      "tsgo",
      "typstyle",
      "shfmt",
      "tailwindcss-language-server",
      "terraform-ls",
      -- "typescript-language-server",
      -- "prettierd",
      "jq",
      "yaml-language-server",
      -- "vtsls",
    },
  },
}
